name: Continuous integration example

on: 
  push:

  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        java: ['8', '11', '17', '19']
    steps:
      - uses: actions/checkout@v3
      - name: ${{matrix.os}} -> Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
      - run: mvn test
